services:
  web:
    image: containers.intersystems.com/intersystems/iris-community:latest
    build:
      context: .
      dockerfile: Dockerfile
    env:
      - key: IRIS_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://${RENDER_EXTERNAL_URL}
    disk:
      name: iris-data
      mountPath: /opt/irisapp/data
      sizeGB: 10
    healthcheck:
      path: /api/monitor/status
      interval: 30s
      timeout: 10s
      retries: 3
    startCommand: iris start IRIS