services:
  web:
    image: intersystems/iris-community:latest
    build:
      context: .
      dockerfile: ./Backend/Dockerfile  # Make sure this path exactly matches your directory structure
    env:
      - key: IRIS_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://${RENDER_EXTERNAL_URL}
    disk:
      name: iris-data
      mountPath: /opt/irisapp/data
      sizeGB: 10
    healthcheck:
      path: /api/monitor/status
      interval: 30s
      timeout: 10s
      retries: 3
    buildCommand: |
      # Build frontend
      cd Frontend && npm install && npm run build
      # Create the csp directory if it doesn't exist
      mkdir -p Backend/csp
      # Copy frontend build to a directory that will be served by IRIS
      cp -r Frontend/build/* Backend/csp/
    startCommand: iris start IRIS